### ISSUE TITLE
"Uncaught TypeError: Illegal constructor" when using uncompressed src

### ISSUE THREAD

**Issue by abubelinha** [ruven/iipmooviewer#83]
In the context described in #81, I am trying to use the uncompressed js files to see if I can modify something.

I successfully changed `mootools.min.js` by `mootools.js` and things keep working.
My `src` path contains all 10 `.js` files in repo [iipmooviewer/src](https://github.com/ruven/iipmooviewer/tree/master/src) (`iipmooviewer-2.0.js`, mootols core & more, etc) plus `lang` and `protocols` subpaths.
But when I change from `js/iipmooviewer-2.0-min.js` to `src/iipmooviewer-2.0.js` I get this error:

> Uncaught TypeError: Illegal constructor
>     at Object.initialize (iipmooviewer-2.0.js:163:25)
>     at wrapper.extend.$owner (ajax.googleapis.com_ajax_libs_mootools_1.6.0_mootools.js:1723:23)
>     at new <anonymous> (ajax.googleapis.com_ajax_libs_mootools_1.6.0_mootools.js:1681:51)
>     at iiipmooviewer.htm:99:5

This is iipmooviewer-2.0.js:162 (error raised in line 163: `this.navigation = Navigation(...`):
```javascript
    if( (typeof(Navigation)==="function") ){
      this.navigation = Navigation({ showNavWindow:options.showNavWindow,
					 showNavButtons: options.showNavButtons,
					 navWinSize: options.navWinSize,
				         showCoords: options.showCoords,
					 prefix: this.prefix,
					 navigation: options.navigation
				       });
    }
```
This is iipmooviewer.htm:99 from #81:

```javascript
    new IIPMooViewer( "viewer", {
	server: server,
	image: image,
	protocol: "IIIF",
	credit: credit,
	scale: 23.0
    });
```
Sorry @ruven I guess this must be some stupid mistake I am doing. I tried with both [mootools.js](https://ajax.googleapis.com/ajax/libs/mootools/1.6.0/mootools.js) alone and later combining `src/mootools-core-1.6.0.js`+`src/mootools-more-1.6.0.js`, but nothing changes.

Thanks in advance
@abubelinha

**Comment by abubelinha** [comment]
OK, I realized there is a different `index-dev.html` file with [many lines I was missing](https://github.com/ruven/iipmooviewer/blob/master/index-dev.html#L53-L81):

```html
  <!-- Load our protocols -->  
  <script src="src/protocols/deepzoom.js"></script>
  <script src="src/protocols/djatoka.js"></script>
  <script src="src/protocols/iip.js"></script>
  <script src="src/protocols/zoomify.js"></script>
  <script src="src/protocols/iiif.js"></script>

  <!-- Load our various components -->
  <script src="src/blending.js"></script>
  <script src="src/navigation.js"></script>
  <script src="src/scale.js"></script>
  <script src="src/touch.js"></script>
  <script src="src/annotations.js"></script>
  <script src="src/annotations-edit.js"></script>

  <!-- Load our language files -->
  <script src="src/lang/help.de.js"></script>
  <script src="src/lang/help.en.js"></script>
  <script src="src/lang/help.es.js"></script>
  <script src="src/lang/help.et.js"></script>
  <script src="src/lang/help.fr.js"></script>
  <script src="src/lang/help.gr.js"></script>
  <script src="src/lang/help.it.js"></script>
  <script src="src/lang/help.nl.js"></script>
  <script src="src/lang/help.pt.js"></script>
  <script src="src/lang/help.ru.js"></script>
  <script src="src/lang/help.se.js"></script>
  <script src="src/lang/help.tr.js"></script>
  <script src="src/lang/help.zh.js"></script>  

```
